<?php

/**
 * @file
 * Primary module hooks for os2web_kle module.
 */

use Drupal\feeds\Entity\Feed;
use Drupal\os2web_kle\Form\SettingsForm;

/**
 * Implements hook_cron().
 */
function os2web_kle_cron() {
  /** @var \Drupal\Core\State\StateInterface $state */
  $state = \Drupal::service('state');
  $lastImport = $state->get('os2web_kle.import_last_run');

  $config = \Drupal::config(SettingsForm::$configName);
  $days = $config->get('import_schedule');

  $next_scheduled_run = strtotime("+$days days", $lastImport);

  if ($next_scheduled_run <= time()) {
    os2web_kle_import_run();
  }
}

/**
 * Runs the import process.
 */
function os2web_kle_import_run() {
  /** @var \Drupal\os2web_kle\Services\KleService $kleService */
  $kleService = \Drupal::service('os2web_kle.service');

  // Getting KLE xml.
  if ($xml = $kleService->getXml()) {

    // Start converting file to a Feed importer friendly format.
    $feedsXml = $kleService->convertXmlToFeeds($xml);

    // Write XML file locally.
    $kleService->writeKleFeedsFile($feedsXml);

    // Set timestamp for when import was last run and when to run next.
    /** @var \Drupal\Core\State\StateInterface $state */
    $state = \Drupal::service('state');

    $state->set('os2web_kle.import_last_run', time());

    \Drupal::logger('os2web_kle')
      ->debug('XML successfully converted and saved as feeds XML file');
  }
  else {
    \Drupal::logger('os2web_kle')
        ->error('XML file conversion error');
  }
}

/**
 * Implements hook_modules_installed().
 */
function os2web_kle_modules_installed($modules) {
  if (in_array('feeds', $modules) && in_array('os2web_kle', $modules)) {
    // Creating feed importer.
    $feed = Feed::create([
      'title' => 'KLE importer',
      'type' => 'os2web_kle_import',
      'source' => 'public://kle.xml',
      'uid' => 1
    ]);

    $feed->save();
  }
}
